<a href="https://colab.research.google.com/github/Shruthi-Yerragolla/NASSCOM/blob/main/Nasscom_1/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

In [3]:
print("Hello, Python!")  # This is a comment

# Indentation defines blocks
if True:
    print("This is indented correctly.")
else:
    print("This won't run.")

Hello, Python!
This is indented correctly.


In [8]:
name = "Alice"
age = 25
height = 5.6

# Print values
print("Name:", name)
print("Age:", age)
print("Height:", height)

# Variables are dynamically typed
name = 123  # Now 'name' holds an integer
print("New value of name:", name)


Name: Alice
Age: 25
Height: 5.6
New value of name: 123


In [9]:
a = 10
print(type(a))


<class 'int'>


In [10]:
b = 3.14
print(type(b))



<class 'float'>


In [14]:
c = "python"
print(type(c))

# Boolean
d = True
print(type(d))

# List
e = [1, 2, 3, "four"]
print(type(e), e)

# Dictionary
f = {"name": "Alice", "age": 25}
print(type(f), f)

<class 'str'>
<class 'bool'>
<class 'list'> [1, 2, 3, 'four']
<class 'dict'> {'name': 'Alice', 'age': 25}


In [15]:
user_name = input("Enter your name: ")
print("Hello,", user_name)

Enter your name: shruthi
Hello, shruthi


In [16]:
user_age = int(input("Enter your age: "))
print("You will be", user_age + 1, "next year.")

Enter your age: 18
You will be 19 next year.


In [26]:

import os

# Get current working directory
print("Current Directory:", os.getcwd())

# List files and directories in current directory
print("Files and Folders:", os.listdir())

# Create a new folder
os.mkdir("demo_folder")  # Creates folder named 'demo_folder'

# Rename a folder
os.rename("demo_folder", "renamed_folder")

# Remove a folder (make sure it's empty)
os.rmdir("renamed_folder")


Current Directory: /content
Files and Folders: ['.config', 'sample_data']


In [20]:
from datetime import datetime, date, timedelta

# Current date and time
now = datetime.now()
print("Now:", now)

# Only today's date
today = date.today()
print("Today's Date:", today)

# Create a specific date
dob = date(2000, 1, 1)
print("DOB:", dob)

# Date arithmetic
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Tomorrow:", tomorrow)

# Format date to string
formatted = now.strftime("%d-%m-%Y %H:%M:%S")
print("Formatted DateTime:", formatted)

Now: 2026-07-30 08:32:08.852408
Today's Date: 2026-07-30
DOB: 2000-01-01
Yesterday: 2026-07-29
Tomorrow: 2026-07-31
Formatted DateTime: 30-07-2026 08:32:08


In [21]:
import random

# Generate random integer between 1 and 100
print("Random Int:", random.randint(1, 100))

# Generate random float between 0 and 1
print("Random Float:", random.random())

# Choose a random item from a list
colors = ['red', 'green', 'blue']
print("Random Color:", random.choice(colors))

# Shuffle a list
random.shuffle(colors)
print("Shuffled List:", colors)

# Generate a random sample of multiple items
print("Sample:", random.sample(range(1, 50), 5))




Random Int: 5
Random Float: 0.5940902477542275
Random Color: green
Shuffled List: ['green', 'red', 'blue']
Sample: [45, 9, 43, 41, 38]


In [22]:

from collections import Counter

# Count occurrences of elements in a list
fruits = ['apple', 'banana', 'apple', 'orange', 'banana', 'apple']
count = Counter(fruits)
print("Fruit Count:", count)


Fruit Count: Counter({'apple': 3, 'banana': 2, 'orange': 1})


In [ ]:
from collections import defaultdict

# Returns a default value for missing keys
marks = defaultdict(lambda: 0)
marks['Math'] = 90
marks['Science'] = 80
print("English Marks (not set):", marks['English'])  # Returns 0


In [23]:
from collections import namedtuple

# Create a Point object with x and y
Point = namedtuple('Point', 'x y')
p1 = Point(10, 20)
print("Point:", p1)
print("x:", p1.x, "y:", p1.y)



Point: Point(x=10, y=20)
x: 10 y: 20


In [24]:
from collections import deque

# Double-ended queue
dq = deque([1, 2, 3])
dq.append(4)        # Add to right
dq.appendleft(0)    # Add to left
dq.pop()            # Remove from right
dq.popleft()        # Remove from left
print("Deque after operations:", dq)


Deque after operations: deque([1, 2, 3])


In [28]:
# 🔹 1. DEFINING A BASIC FUNCTION

# A function is a block of code that performs a task and can be reused.

def greet():
    print("Hello! Welcome to Python Functions.")

# Calling the function
greet()

Hello! Welcome to Python Functions.


In [30]:
# 🔹 2. FUNCTION WITH PARAMETERS

def greet_user(name):
    print(f"Hello, {name}!")

greet_user("Alice")
greet_user("Bob")  # You can reuse the function with different arguments


Hello, Alice!
Hello, Bob!


In [31]:
# 🔹 3. FUNCTION WITH DEFAULT PARAMETERS

def greet_user(name="Guest"):
    print(f"Welcome, {name}!")

greet_user()         # Uses default
greet_user("Ravi")   # Overrides default




Welcome, Guest!
Welcome, Ravi!


In [32]:
# 🔹 5. USING *args (VARIABLE NUMBER OF POSITIONAL ARGUMENTS)

# *args lets you pass any number of positional arguments as a tuple

def print_names(*names):
    print("Names passed:", names)
    for name in names:
        print("Hello", name)

print_names("Alice", "bob", "Charlie")




Names passed: ('Alice', 'bob', 'Charlie')
Hello Alice
Hello bob
Hello Charlie


In [33]:
# 🔹 6. USING **kwargs (VARIABLE NUMBER OF KEYWORD ARGUMENTS)

# **kwargs lets you pass any number of keyword arguments as a dictionary

def print_info(**info):
    print("User Info:")
    for key, value in info.items():
        print(f"{key} = {value}")

print_info(name="Alice", age=25, city="Delhi")


User Info:
name = Alice
age = 25
city = Delhi


In [35]:
# 🔹 7. COMBINING *args AND **kwargs

def show_details(*args, **kwargs):
    print("Args:", args)
    print("Kwargs:", kwargs)

show_details(1, 2, 3, name="Ravi", city="Mumbai")

Args: (1, 2, 3)
Kwargs: {'name': 'Ravi', 'city': 'Mumbai'}


In [36]:
# 🔹 8. FUNCTION NESTING (CALL ONE FUNCTION INSIDE ANOTHER)

def multiply(a, b):
    return a * b

def square(n):
    return multiply(n, n)

print("Square of 4:", square(4))




Square of 4: 16


In [37]:
# 🔹 1. LISTS
# A list is an ordered, mutable collection that allows duplicates

fruits = ['apple', 'banana', 'cherry', 'apple']
print("Original list:", fruits)

# Accessing elements by index
print("First fruit:", fruits[0])



Original list: ['apple', 'banana', 'cherry', 'apple']
First fruit: apple


In [38]:
# Adding an item
fruits.append('orange')
print("After appending:", fruits)



After appending: ['apple', 'banana', 'cherry', 'apple', 'orange']


In [39]:
# Removing an item
fruits.remove('banana')
print("After removing banana:", fruits)

# List length
print("Number of fruits:", len(fruits))


After removing banana: ['apple', 'cherry', 'apple', 'orange']
Number of fruits: 4


In [40]:
# 🔹 2. TUPLES
# A tuple is an ordered, immutable collection that allows duplicates

dimensions = (10, 20, 30)
print("Tuple:", dimensions)




Tuple: (10, 20, 30)


In [41]:
# Accessing elements
print("Second element:", dimensions[1])

# Tuples are immutable: can't add/remove
# dimensions[1] = 50 → This would raise an error


Second element: 20


In [42]:
# 🔹 3. SETS
# A set is an unordered, mutable collection with NO duplicates

unique_numbers = {1, 2, 3, 2, 1}
print("Set (no duplicates):", unique_numbers)



Set (no duplicates): {1, 2, 3}


In [44]:
# Adding elements
unique_numbers.add(4)
print("After adding 4:", unique_numbers)





After adding 4: {1, 2, 3, 4}


In [45]:
# Removing elements
unique_numbers.remove(2)
print("After removing 2:", unique_numbers)


After removing 2: {1, 3, 4}


In [47]:

# Set operations
set_a = {1, 2, 3}
set_b = {3, 4, 5}
print("Union:", set_a | set_b)
print("Intersection:", set_a & set_b)
print("Difference (A - B):", set_a - set_b)

Union: {1, 2, 3, 4, 5}
Intersection: {3}
Difference (A - B): {1, 2}


In [48]:
# 🔹 4. DICTIONARIES
# A dictionary stores key-value pairs (like a map or JSON object)

student = {
    'name': 'Alice',
    'age': 21,
    'course': 'Python'
}
print("Dictionary:", student)


Dictionary: {'name': 'Alice', 'age': 21, 'course': 'Python'}


In [49]:
# Access value by key
print("Student name:", student['name'])


Student name: Alice


In [50]:

# Add or update value
student['grade'] = 'A'
print("After adding grade:", student)

# Remove a key
del student['age']
print("After deleting age:", student)

# Loop through dictionary
for key, value in student.items():
    print(f"{key}: {value}")


After adding grade: {'name': 'Alice', 'age': 21, 'course': 'Python', 'grade': 'A'}
After deleting age: {'name': 'Alice', 'course': 'Python', 'grade': 'A'}
name: Alice
course: Python
grade: A


In [52]:
# Bonus: Dictionary from two lists using zip()
keys = ['id', 'name', 'marks']
values = [101, 'John', 88]
student_info = dict(zip(keys, values))
print("Student Info from zip:", student_info)


Student Info from zip: {'id': 101, 'name': 'John', 'marks': 88}


In [53]:
# 🔹 1. ARRAY CREATION FUNCTIONS
# -----------------------------------------------------------

# arange(): Create range of numbers like Python's range()
arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)


Array using arange: [0 2 4 6 8]


In [54]:
# linspace(): Create evenly spaced values between two limits
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)



Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [55]:
# reshape(): Change shape without changing data
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

# flatten(): Convert multi-dimensional array to 1D
print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [56]:
# -----------------------------------------------------------
# 🔹 2. AGGREGATE FUNCTIONS
# -----------------------------------------------------------

data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)


Original Data:
 [[5 8 9]
 [2 4 6]]


In [57]:

print("Sum of all elements:", np.sum(data))             # Total sum
print("Column-wise sum:", np.sum(data, axis=0))         # Sum along columns
print("Row-wise mean:", np.mean(data, axis=1))          # Average of each row
print("Max value:", np.max(data))                       # Maximum value


Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9


In [58]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))                       # Minimum value
print("Standard Deviation:", np.std(data))              # Spread of

Index of max value (flattened): 2
Min value: 2
Standard Deviation: 2.3570226039551585


In [59]:
# -----------------------------------------------------------
# 🔹 3. SORTING AND SEARCHING
# -----------------------------------------------------------

a = np.array([3, 1, 7, 2, 9])
print("Original Array:", a)


Original Array: [3 1 7 2 9]


In [60]:

# Sort array values
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)

# Find indices where condition is True (value > 4)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])



Sorted Array: [1 2 3 7 9]
Indices where value > 4: (array([2, 4]),)
Values > 4: [7 9]


In [61]:

# -----------------------------------------------------------
# 🔹 4. BROADCASTING IN NUMPY
# -----------------------------------------------------------

# Broadcasting allows NumPy to perform operations between arrays of different shapes
A = np.array([[1, 2], [3, 4]])  # 2x2 matrix
B = np.array([10, 20])          # 1D array with 2 elements

print("Matrix A:\n", A)
print("Vector B:", B)


Matrix A:
 [[1 2]
 [3 4]]
Vector B: [10 20]


In [63]:
# B is broadcasted to each row of A
C = A + B
print("Broadcasted Addition Result:\n", C)



Broadcasted Addition Result:
 [[11 22]
 [13 24]]


In [64]:

# -----------------------------------------------------------
# 🔹 5. CONDITIONAL OPERATIONS
# -----------------------------------------------------------

nums = np.array([1, 2, 3, 4, 5])

# Create boolean mask for condition nums > 3
mask = nums > 3
print("Mask (nums > 3):", mask)



Mask (nums > 3): [False False False  True  True]


In [65]:
# Use mask to filter values
filtered = nums[mask]
print("Filtered values:", filtered)

# np.where: apply conditional logic
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)

Filtered values: [4 5]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [67]:



arr_orig = np.array([10, 20, 30])

# Creating a view (shares memory)
arr_view = arr_orig[:]
arr_view[0] = 99  # This change affects original
print("Original After View Change:", arr_orig)


Original After View Change: [99 20 30]


In [68]:
# Creating a copy (independent)
arr_copy = arr_orig.copy()
arr_copy[0] = 55  # This does NOT affect original
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)


Original After Copy Change: [99 20 30]
Copy: [55 20 30]


In [69]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Vertical stack (as rows)
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [70]:
# Horizontal stack (as columns)
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)

# Split an array into 3 sub-arrays
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)



Horizontal Stack:
 [1 2 3 4 5 6]
Split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [71]:
# Random integers from 0 to 100 in 3x3 matrix
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)

# Random values from standard normal distribution (mean=0, std=1)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)


Random Integers:
 [[81 82 79]
 [61 64 77]
 [78 84 50]]
Random Normal Distribution:
 [[ 0.81588842  0.97917676  0.65521441  0.64736955]
 [-1.05194828  0.9663692   0.68670112  0.64070262]]


In [72]:
# Random sampling from a custom list
choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)

# Setting a seed ensures reproducible random results
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())

Random Choices: [7 1 7 3 5]
Seeded Random Number: 0.3745401188473625


In [74]:

# Create a sample 1D array
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)

# Access single elements by index
print("Element at index 0:", arr[0])        # 10
print("Element at last index:", arr[-1])    # 60

Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60


In [75]:

# Slice elements [start:stop] (stop is exclusive)
print("Slice from index 1 to 4:", arr[1:4])  # [20, 30, 40]

# Slice with step
print("Every second element:", arr[::2])     # [10, 30, 50]

# Reverse array
print("Reversed array:", arr[::-1])          # [60, 50, ..., 10]


Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [76]:
# -----------------------------------------------------------
# 🔹 10A. 2D ARRAY INDEXING AND SLICING
# -----------------------------------------------------------

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

# Access element at row 1, column 2
print("Element at (1,2):", matrix[1, 2])  # 6

# Get entire first row
print("First row:", matrix[0, :])  # [1, 2, 3]

# Get entire second column
print("Second column:", matrix[:, 1])  # [2, 5, 8]

# Slice sub-matrix (top-left 2x2 block)
print("Top-left 2x2 block:\n", matrix[:2, :2])  # [[1,2],[4,5]]



Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [77]:

# -----------------------------------------------------------
# 🔹 10B. BOOLEAN INDEXING
# -----------------------------------------------------------

arr = np.array([5, 10, 15, 20, 25, 30])

# Create a boolean mask for values > 15
mask = arr > 15
print("Boolean Mask:", mask)

# Use mask to filter elements
print("Values greater than 15:", arr[mask])  # [20, 25, 30]

# Combine conditions
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])  # [20, 30]

Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [20 30]
